kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  resourceVersion: '658926084'
  name: welcomeservice
  uid: 60467d83-44ed-45d6-a297-1aef66793c89
  creationTimestamp: '2022-02-14T11:59:31Z'
  generation: 6
  managedFields:
    - manager: oc.exe
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-02-14T11:59:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:selector':
            .: {}
            'f:deploymentconfig': {}
          'f:strategy':
            'f:activeDeadlineSeconds': {}
            'f:rollingParams':
              .: {}
              'f:intervalSeconds': {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
              'f:timeoutSeconds': {}
              'f:updatePeriodSeconds': {}
            'f:type': {}
          'f:template':
            .: {}
            'f:metadata':
              .: {}
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:creationTimestamp': {}
              'f:labels':
                .: {}
                'f:deploymentconfig': {}
            'f:spec':
              .: {}
              'f:containers':
                .: {}
                'k:{"name":"welcomeservice"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":9090,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-02-14T11:59:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:details':
            .: {}
            'f:causes': {}
            'f:message': {}
          'f:latestVersion': {}
    - manager: member-operator
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-02-14T23:59:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:replicas': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-02-15T06:31:45Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            'k:{"type":"Available"}':
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: ssenthilkumarit-dev
  labels:
    app: welcomeservice
    app.kubernetes.io/component: welcomeservice
    app.kubernetes.io/instance: welcomeservice
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - welcomeservice
        from:
          kind: ImageStreamTag
          namespace: ssenthilkumarit-dev
          name: 'welcomeservice:latest'
        lastTriggeredImage: >-
          ssenthilkumarit/welcomeservice@sha256:6d978f9ef4b1d9c86a93b7e78ab283f81ec412273ea794b7df938475e6c5a822
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentconfig: welcomeservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: welcomeservice
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: welcomeservice
          image: >-
            ssenthilkumarit/welcomeservice@sha256:6d978f9ef4b1d9c86a93b7e78ab283f81ec412273ea794b7df938475e6c5a822
          ports:
            - containerPort: 9090
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 6
  details:
    message: config change
    causes:
      - type: ConfigChange
  availableReplicas: 1
  unavailableReplicas: 0
  latestVersion: 1
  updatedReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-02-14T11:59:41Z'
      lastTransitionTime: '2022-02-14T11:59:41Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "welcomeservice-1" successfully rolled out
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-02-15T07:20:09Z'
      lastTransitionTime: '2022-02-15T07:20:09Z'
      message: Deployment config has minimum availability.
  replicas: 1
  readyReplicas: 1
